Функциональность «Общие фильмы».
impossible97/java-filmorate pull request #19
Opened 2023-09-14 06:55 UTC by AlekseiZubkov

2023-09-14 08:54 UTC, impossible97 requested changes

2023-09-14 08:54 UTC, impossible97 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Рекомендация
Лучше импортировать классы по отдельности, как это было изначально в моем варианте, а не использовать символ * для импорта всех классов из пакета. Импорт отдельных классов позволяет явно указать, какие классы будут использоваться в коде. Это делает код более понятным и удобным для чтения. А так же если ты импортируешь лишние классы с помощью символа *, компилятору нужно будет искать и загружать дополнительные классы, что может замедлить процесс компиляции и сборки. Да и банально это съедает больше памяти, чем нужно.

2023-09-14 08:54 UTC, impossible97 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findFilmsByLikes(@RequestParam("userId") int userId, @RequestParam("friendId") int friendId) {
Измени пожалуйста название метода
Видимо ты забыл )

2023-09-14 08:54 UTC, impossible97 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +import java.sql.*;
Смотри комментарий выше

2023-09-14 16:40 UTC, AlekseiZubkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Исправил , это делает автоматически команда Ctr+Alt+O

2023-09-14 16:40 UTC, AlekseiZubkov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findFilmsByLikes(@RequestParam("userId") int userId, @RequestParam("friendId") int friendId) {
Исправил.

2023-09-14 16:40 UTC, AlekseiZubkov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorageImpl.java
> +import java.sql.*;
Исправил.

2023-09-14 18:35 UTC, impossible97 approved these changes

2023-09-18 14:48 UTC, Ruslan-Yusov approved these changes

2023-09-18 14:50 UTC, merged